Update ansible to stable channel
stolostron/application-ui pull request #1417
Opened 2022-02-16 21:14 UTC by fxiang1

Signed-off-by: Feng Xiang <fxiang@redhat.com>

- Update ansible to stable channel

2022-02-17 16:06 UTC, chenz4027 commented on tests/cypress/templates/ansible_yaml/ansible-subscription.yaml
> +  name: ansible-automation-platform-operator
If we change the name here, we may also need to change it in start-cypress-tests.sh as it deletes the operator with name

2022-02-17 16:06 UTC, chenz4027 requested changes
@fxiang1

2022-02-17 18:25 UTC, fxiang1 commented on tests/cypress/templates/ansible_yaml/ansible-subscription.yaml
> +  name: ansible-automation-platform-operator
Thanks @chenz4027. That's a good catch. I made the change now.

2022-02-17 19:52 UTC, fxiang1 commented
/test e2e-cluster

2022-02-17 21:11 UTC, fxiang1 commented
/test e2e-cluster

2022-02-22 14:56 UTC, fxiang1 commented
@chenz4027 Can you review this again? The e2e test passed now. Thanks.

2022-02-22 15:05 UTC, chenz4027 approved these changes
lgtm!

2022-02-22 15:06 UTC, merged